### ISSUE TITLE
JSONDecodeError 

### ISSUE THREAD

**Issue by rishrishrish** [Mayur57/twitter-nuke#2]
Hi im having an error, the following is what i got after running the script : 
``` 
>> Processing your tweet.js file and converting it to a JSON.

>> Processing tweet.js file

>> Converting to processable JSON
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 111, in _get_module_details
    import(pkg_name)
  File "C:\Users\risha\Desktop\fx\scriptt.py", line 132, in <module>
    parse_json(JSON_FILE, LIKES, RETWEETS)
  File "C:\Users\risha\Desktop\fx\scriptt.py", line 68, in parse_json
    data = json.load(jfd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64qbz5n2kfra8p0\lib\json\__init.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64qbz5n2kfra8p0\lib\json\__init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 6)
```

**Comment by mayur57** [comment]
Hello @rishrishrish, thanks for opening this issue. Ensure that you are running this script inside the directory of your Twitter archive. 

If it does not work even after following all the steps, I'll have to take a look at your tweet.js file to check whether the format has changed. See if this works though.

**Comment by rishrishrish** [comment]
@Mayur57 i created a separate folder, and have placed the tweet.js and script there, and im sure the i have the directories correct.
Also i checked the tweet.js and removed all non ascii characters already (like emojis, and other special characters) otherwise i was getting error a step before this, plus the deleter.json file also got created, so is the issue still in tweet.js file?

**Comment by rishrishrish** [comment]
@Mayur57 sorry to ping you again and again but i need to get done with this thing as soon as possible.

**Comment by rishrishrish** [comment]
still waiting -.-

**Comment by mayur57** [comment]
Hello, sorry for the delay. I'll look into it and update the issue soon.
