### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ghost** [Mayur57/twitter-nuke#7]
After fixing a couple of problems I got the script to run and mostly work, but I did notice this error:

```
Exception in thread Thread-31 (delete_tweets):
Traceback (most recent call last):
T - Deleted: 856534486653308932
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
T - Deleted: 826123225163845632
T - Deleted: 464801561127178240
T - Deleted: 1100834889958608896
T - Deleted: 1018653649478832128
T - Deleted: 769551237721251840
T - Deleted: 883419519833788417
T - Deleted: 27517911400718336
T - Deleted: 4160500189
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
T - Deleted: 949445145539334145
T - Deleted: 964967785540603905
T - Deleted: 930911513614913536
T - Deleted: 1141781722209501185
T - Deleted: 906531239125032960
    self._target(*self._args, **self._kwargs)
T - Deleted: 1071462771001319425
T - Deleted: 1241758022571044865
  File "/home/rsholmes/Downloads/twitter-nuke/src/delete-script-rsh.py", line 99, in delete_tweets
T - Deleted: 142232664936689665
T - Deleted: 233966575911305216
    api.destroy_status(int(tweets_to_delete[i]))
IndexError: list index out of range
```

**Comment by 65156** [comment]
still working, errored on a small number of tweets, but out of 2500, managed to get 2495 of them.
